name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache ISOs
      id: cache-isos
      uses: actions/cache@v4
      with:
        path: iso
        key: ${{ runner.os }}-iso-${{ hashFiles('iso_urls.txt') }}

    - name: Download ISOs
      if: steps.cache-isos.outputs.cache-hit != 'true'
      run: ./scripts/download-isos.sh

    - name: Build and Verify Docker images
      env:
        DOCKER_IMAGE_PREFIX: ${{ secrets.DOCKER_IMAGE_PREFIX }}
      run: |
        # The build script requires sudo, so we need to run it with sudo
        # and make sure the environment variables are passed.
        sudo -E ./scripts/builds.sh

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push the Docker images to Docker Hub
      run: |
        while read IMAGE_TAG; do
          ./scripts/verify-image.sh "$IMAGE_TAG"
          docker push "$IMAGE_TAG"
        done < image_tags.txt